### ISSUE TITLE
library included in head

### ISSUE THREAD

**Issue by sn1987a** [eduardomb/jquery-panelslider#3]
Hello,

When I include the library in the body section of the page, the sliding function work correctly. But when I include it in the head of the page, it does not work at all. How do I do to make the include in the head ?

I use this code to include the library:
<script src="eduardomb-jquery-panelslider-0.1.0-0/jquery.panelslider.js"></script>

Regards,

**Comment by Nilpo** [comment]
When you load the scripts in the page head, the panel overlaps because the body margin never adjusts when the panel opens.  Also, the "ps-active-panel" class does not get removed when then panel is closed.  The panel's css remains display:block instead of reverting to display:none.  It behaves like a dynamically created element would when a scripts is loaded in the page head.  Since it's JavaScript best practice to load scripts at the bottom of the body, it seems like a moot point to figure out a workaround for it, in my opinion.

**Comment by eduardomb** [comment]
@sn1987a this issue was fixed on `1.0.0`. There are breaking changes though. I've updated **README.md** with new instructions of how to use the plugin. Sorry for taking this long to answer. Please let me know if you have trouble upgrading.
