### ISSUE TITLE
Panel slide inside a container (div)

### ISSUE THREAD

**Issue by JobaDiniz** [eduardomb/jquery-panelslider#6]
I want to open the panel within a container, not in entire page. How to accomplish thatw

**Comment by Nilpo** [comment]
I toyed with this a little bit.  It would take a bit of a rewrite.  The movement relies on fixed CSS positioning.  If this ends up being a feature, rather than having a container option, I would suggest autodetecting the panel's parent object.  Then you could change it by simply placing the element on the page inside of the parent it should slide in.

I've written an implementation using `options.container`, but it requires some CSS adjustments to get the positioning right.  The slider is working inside the specified parent now though.

**Comment by eduardomb** [comment]
Hi, sorry for taking too long to answer. If you are still willing to use the plugin the good news is since version 1.0.0 animation and positioning are handled by user's CSS.

This gives you power to customize the panel positioning in any way you want, e.g., inside a container. Checkout *example.html* to see a CSS implementation of left and right panels.
