### ISSUE TITLE
Up Down sliding

### ISSUE THREAD

**Issue by naman** [eduardomb/jquery-panelslider#7]
I think, it should support up and down sides as well. I can try it. :)

**Comment by Nilpo** [comment]
@namchester Have you tried this yet?  If not, I may take a stab at an implementation of it.

**Comment by egfx** [comment]
Please try it. There are many left right sliders but not a lot of quality up down ones. In fact, another version of this slider as an option would be even more amazing. http://app-folders.com/

**Comment by eduardomb** [comment]
Hi, sorry for taking too long to answer. If you are still willing to use the plugin the good news is since version `1.0.0` animation and positioning are handled by user's CSS.

This gives you power to customize the panel positioning in any way you want, e.g., on the top or bottom of the page. There is a CSS implementation of left / right panels in *example.html*. In this example, if you change the **translateX** properties to **translateY** and and swap the panel **widht** / **height** properties you'll get the Up / Down sliding effect.

Let me know if you face any problems when doing this. I'll try to add another example file with this in the next days.
